name: "Workflow 2: Approve and Merge PR"

on:
  repository_dispatch:
    types: [version_bump_ready]

jobs:
  validate-and-approve:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.validate.outputs.version }}
      pr_number: ${{ steps.validate.outputs.pr_number }}
      test_mode: ${{ steps.validate.outputs.test_mode }}
    steps:
      - name: Validate and approve PR
        id: validate
        env:
          GITHUB_TOKEN: ${{ secrets.APPROVER_TOKEN }}
        run: |
          set -e
          
          # Extract and validate data
          PR_NUMBER="${{ github.event.client_payload.outputs.pr_number }}"
          VERSION="${{ github.event.client_payload.version }}"
          TEST_MODE="${{ github.event.client_payload.outputs.test_mode }}"
          MANUAL_APPROVAL="${{ github.event.client_payload.outputs.manual_approval }}"
          
          # Validate required data
          [[ -n "$PR_NUMBER" && -n "$VERSION" ]] || {
            echo "ERROR: Missing required data in payload" >&2
            exit 1
          }
          
          # Verify PR exists and is open
          gh pr view "$PR_NUMBER" --json state --jq '.state' | grep -q "^OPEN$" || {
            echo "ERROR: PR #$PR_NUMBER not found or not open" >&2
            exit 1
          }
          
          # Handle manual approval mode
          if [[ "$MANUAL_APPROVAL" == "true" ]]; then
            echo "Manual approval required. Skipping auto-approval."
            exit 0
          fi
          
          # Auto-approve and enable merge
          gh pr review "$PR_NUMBER" --approve \
            --body "✅ Automated approval for release $VERSION$([ "$TEST_MODE" == "true" ] && echo " [TEST MODE]")"
          
          gh pr merge "$PR_NUMBER" --auto --squash
          
          # Output values
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "test_mode=$TEST_MODE" >> $GITHUB_OUTPUT

  wait-and-dispatch:
    needs: validate-and-approve
    # Skip if manual approval is required
    if: github.event.client_payload.outputs.manual_approval != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for merge and trigger publish
        env:
          VERSION: ${{ needs.validate-and-approve.outputs.version }}
          PR_NUMBER: ${{ needs.validate-and-approve.outputs.pr_number }}
          TEST_MODE: ${{ needs.validate-and-approve.outputs.test_mode }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          
          # Wait for merge (2 minutes max)
          for ((i=0; i<24; i++)); do
            PR_DATA=$(gh pr view "$PR_NUMBER" --json state,mergeCommit --jq '{state: .state, sha: .mergeCommit.oid}')
            
            if [[ $(echo "$PR_DATA" | jq -r '.state') == "MERGED" ]]; then
              MERGE_SHA=$(echo "$PR_DATA" | jq -r '.sha')
              break
            fi
            
            [[ $(echo "$PR_DATA" | jq -r '.state') == "CLOSED" ]] && {
              echo "ERROR: PR #$PR_NUMBER was closed without merging" >&2
              exit 1
            }
            
            sleep 5
          done
          
          [[ -n "$MERGE_SHA" ]] || {
            echo "ERROR: PR #$PR_NUMBER merge timeout after 120s" >&2
            exit 1
          }
          
          # Dispatch to publish workflow with test mode
          gh api repos/${{ github.repository }}/dispatches \
            --field event_type="pr_merged_ready" \
            --field client_payload[version]="$VERSION" \
            --field client_payload[outputs][merge_sha]="$MERGE_SHA" \
            --field client_payload[outputs][test_mode]="$TEST_MODE"

      - name: Summary
        env:
          VERSION: ${{ needs.validate-and-approve.outputs.version }}
          PR_NUMBER: ${{ needs.validate-and-approve.outputs.pr_number }}
          TEST_MODE: ${{ needs.validate-and-approve.outputs.test_mode }}
        run: |
          echo "## Workflow 2 Complete" >> $GITHUB_STEP_SUMMARY
          echo "**Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "**PR**: #$PR_NUMBER" >> $GITHUB_STEP_SUMMARY
          if [[ "$TEST_MODE" == "true" ]]; then
            echo "**Mode**: TEST MODE" >> $GITHUB_STEP_SUMMARY
          fi
          if [[ "${{ github.event.client_payload.outputs.manual_approval }}" == "true" ]]; then
            echo "**Status**: Waiting for manual approval" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Status**: Auto-approved and merged" >> $GITHUB_STEP_SUMMARY
            echo "**Next**: Publish workflow triggered" >> $GITHUB_STEP_SUMMARY
          fi
          echo "✅ Complete" >> $GITHUB_STEP_SUMMARY 