name: Release on Merge

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'releases/')
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from branch name
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" \
                    | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' \
                    | head -1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Ensure XCFrameworks present
        run: |
          # Verify primary XCFramework
          if [ ! -d PurchaseConnector.xcframework ]; then
            echo "ERROR: PurchaseConnector.xcframework missing" >&2
            exit 1
          fi
          # Verify dynamic variant
          if [ ! -d Dynamic/PurchaseConnector.xcframework ]; then
            echo "ERROR: Dynamic/PurchaseConnector.xcframework missing" >&2
            exit 1
          fi

      - name: Update Carthage JSONs
        run: ./scripts/update_carthage.sh "${{ env.VERSION }}"

      - name: Update Podspec
        run: ./scripts/update_podspec.sh "${{ env.VERSION }}"

      - name: Update Swift Package manifest
        run: ./scripts/update_spm.sh "${{ env.VERSION }}"

      - name: Commit bumped manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Carthage/*.json PurchaseConnector.podspec Package.swift
          git commit -m "chore: bump version to v${{ env.VERSION }}"
          git push

      - name: Create annotated tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Zip XCFramework artifacts
        run: ./scripts/zip_artifacts.sh

      - name: Draft GitHub Release with XCFramework zips
        uses: softprops/action-gh-release@v1
        with:
          tag_name:    "v${{ env.VERSION }}"
          name:        "v${{ env.VERSION }}"
          draft:       false
          files: |
            purchase-connector-static.xcframework.zip
            purchase-connector-dynamic.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: ./scripts/update_readme.sh "${{ env.VERSION }}"

      - name: Commit README update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "docs: update README for v${{ env.VERSION }}" || echo "No README changes"
          git push
          
      - name: Publish to CocoaPods
        continue-on-error: true
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          gem install cocoapods
          pod repo update
          pod trunk push PurchaseConnector.podspec --allow-warnings --use-libraries

      - name: Check out Dynamic SPM repo on test branch
        uses: actions/checkout@v3
        with:
          repository: AppsFlyerSDK/PurchaseConnector-Dynamic
          token:      ${{ secrets.PC_DYNAMIC_TOKEN }}
          path:       spm-dynamic
          ref:        main
          fetch-depth: 0

      - name: Update Dynamic SPM Package.swift
        run: |
          cp purchase-connector-dynamic.xcframework.zip spm-dynamic/
          cd spm-dynamic
          
          #Compute checksum
          NEW_CHECKSUM=$(swift package compute-checksum purchase-connector-dynamic.xcframework.zip)
          echo "Computed checksum: $NEW_CHECKSUM"
          
          #Update URL version
          sed -i.bak -E "s|url: \"[^\"]+releases/download/[0-9]+\.[0-9]+\.[0-9]+/purchase-connector-dynamic\.xcframework\.zip\"|url: \"https://github.com/AppsFlyerSDK/appsflyer-apple-purchase-connector/releases/download/${VERSION}/purchase-connector-dynamic.xcframework.zip\"|" Package.swift
          
          #Update checksum
          sed -i.bak -E 's|checksum:[[:space:]]*\".*\"|checksum: \"'"${NEW_CHECKSUM}"'\"|' Package.swift
          
          #Push changes and tag
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Package.swift
          git commit -m "chore(spm-dynamic): bump to v${VERSION}" || echo "Nothing to commit"
          git tag -a "v${VERSION}" -m "Release v${VERSION} PurchaseConnector-Dynamic"
          git push origin main
          git push origin "v${VERSION}"

      - name: Draft Dynamic SPM Release
        uses: softprops/action-gh-release@v1
        with:
          repository: AppsFlyerSDK/PurchaseConnector-Dynamic
          tag_name:    "v${{ env.VERSION }}"
          name:        "PurchaseConnector-Dynamic v${{ env.VERSION }}"
          draft:       false
        env:
          GITHUB_TOKEN: ${{ secrets.PC_DYNAMIC_TOKEN }}
